[0m14:16:38.274510 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7183b323c6a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7183b2330fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7183b2332b00>]}


============================== 14:16:38.279043 | 3f8815c8-3f32-4a42-8a7e-aba62730c2b9 ==============================
[0m14:16:38.279043 [info ] [MainThread]: Running with dbt=1.11.0-b3
[0m14:16:38.279876 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'fail_fast': 'False', 'warn_error': 'None', 'empty': 'None', 'write_json': 'True', 'debug': 'False', 'quiet': 'False', 'profiles_dir': '/home/user/.dbt', 'static_parser': 'True', 'no_print': 'None', 'indirect_selection': 'eager', 'log_format': 'default', 'cache_selected_only': 'False', 'partial_parse': 'True', 'log_cache_events': 'False', 'introspect': 'True', 'printer_width': '80', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'log_path': 'logs', 'use_experimental_parser': 'False', 'invocation_command': 'dbt init', 'use_colors': 'True'}
[0m14:18:11.153863 [debug] [MainThread]: Starter project path: /home/user/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m14:18:11.157969 [info ] [MainThread]: 
Your new dbt project "olist_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:18:11.158910 [info ] [MainThread]: Setting up your profile.
[0m14:23:10.171597 [error] [MainThread]: Encountered an error:

[0m14:23:10.174450 [error] [MainThread]: Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/home/user/.local/lib/python3.10/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/user/.local/lib/python3.10/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/user/.local/lib/python3.10/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/user/.local/lib/python3.10/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/home/user/.local/lib/python3.10/site-packages/dbt/task/init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
  File "/usr/lib/python3/dist-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
  File "/usr/lib/python3/dist-packages/click/termui.py", line 150, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m14:23:10.176216 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 391.98645, "process_in_blocks": "165984", "process_kernel_time": 0.218014, "process_mem_max_rss": "179104", "process_out_blocks": "80", "process_user_time": 4.303214}
[0m14:23:10.177057 [debug] [MainThread]: Command `dbt init` failed at 14:23:10.176941 after 391.99 seconds
[0m14:23:10.177802 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7183b323c6a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7183b237c5e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7183b23a8790>]}
[0m14:23:10.178446 [debug] [MainThread]: Flushing usage events
[0m14:23:11.247562 [debug] [MainThread]: An error was encountered while trying to flush usage events
